site_name: Outils et méthodes de développement informatique

nav:
  - Home: index.md
  - Introduction to Git and GitLab: Introduction_git_github.md
theme:
  name: 'flatly'
  logo: docs/img/logo-insa.jpg
  favicon: docs/img/favicon.ico